# Generated by Django 5.2.4 on 2025-07-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
