# Generated by Django 5.2.4 on 2025-07-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
