# Generated by Django 5.2.4 on 2025-08-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
